name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:

  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

  unit_tests:
    needs:
      - install
    steps:
      - name: Unit tests
        run: npm run test:unit

  fonctionnal_tests:
    needs:
      - install
    steps:
      - name: Functionnal tests
        run: |
          docker compose -f ./tests/functionnal/dependencies/docker-compose.yaml up -d
          cd ./
          npm run test:func

  integration_tests:
    needs:
      - install
    steps:
      - name: Integration tests
        run: |
          docker compose -f ./tests/integ/docker-compose.yaml up -d
          cd ./
          npm run test:integ