name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:

  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Install dependencies
        run: |
          npm install
          ls

  unit_tests:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Unit tests
        run: |
          npm run test:unit
          ls

  fonctionnal_tests:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Functionnal tests
        run: |
          docker compose -f ./tests/functionnal/dependencies/docker-compose.yaml up -d
          npm run test:func
          ls

  integration_tests:
    needs:
      - install
    runs-on: ubuntu-latest
    steps:
      - name: Integration tests
        run: |
          docker compose -f ./tests/integ/docker-compose.yaml up -d
          cd ./
          npm run test:integ