name: Run Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
      
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm run test:unit

      - name: Functionnal tests
        run: |
          docker compose -f ./tests/functionnal/dependencies up -d
          cd ./
          npm run test:func

      - name: Integration tests
        run: |
          docker compose -f ./tests/integ up -d
          cd ./
          npm run test:integ